### ISSUE TITLE
OCSPRequest

### ISSUE THREAD

**Issue by Falseclock** [Adapik/CMS#3]
Can you add additional clases to mapping, cause it can be also part of unsiged data?

```php
abstract class OCSPRequest
{
	/*
	    https://tools.ietf.org/html/rfc5280
		OCSPRequest     ::=     SEQUENCE {
			tbsRequest                  TBSRequest,
			optionalSignature   [0]     EXPLICIT Signature OPTIONAL
		}
	*/
	const MAP = [
		'type'     => Identifier::SEQUENCE,
		'children' => [
			'tbsRequest'        => [ 'type' => TBSRequest::MAP ],
			'optionalSignature' => [
				'type'     => Signature::MAP,
				'optional' => true,
				'explicit' => true,
				'constant' => 0,
			],
		],
	];
}

abstract class TBSRequest
{
	/*
		TBSRequest      ::=     SEQUENCE {

		   version             [0]     EXPLICIT Version DEFAULT v1,
		   requestorName       [1]     EXPLICIT GeneralName OPTIONAL,
		   requestList                 SEQUENCE OF Request,
		   requestExtensions   [2]     EXPLICIT Extensions OPTIONAL }

	 */
	const MAP = [
		'type'     => Identifier::SEQUENCE,
		'children' => [
			'version'           => [
				'type'     => Identifier::INTEGER,
				'constant' => 0,
				'optional' => true,
				'explicit' => true,
				'mapping'  => [ 'v1', 'v2', 'v3' ],
				'default'  => 'v1',
			],
			'requestorName'     => [
				'constant' => 1,
				'optional' => true,
				'explicit' => true,
			],
			'requestList'       => [
				'type' => Request::MAP,
			],
			'requestExtensions' => [
									   'constant' => 2,
									   'optional' => true,
									   'explicit' => true,
								   ] + Extensions::MAP,
		],
	];
}

abstract class Request
{
	/**
	 *    Request         ::=     SEQUENCE {
	 *        reqCert                     CertID,
	 *        singleRequestExtensions     [0] EXPLICIT Extensions OPTIONAL
	 *    }
	 */
	const MAP = [
		'type'     => Identifier::SEQUENCE,
		'children' => [
			'reqCert'                 => [ 'type' => CertID::MAP ],
			'singleRequestExtensions' => [
											 'constant' => 0,
											 'optional' => true,
											 'explicit' => true,
										 ] + Extensions::MAP,
		],
	];
}

abstract class CertID
{
	/**
	 *  CertID          ::=     SEQUENCE {
	 *        hashAlgorithm       AlgorithmIdentifier,
	 *        issuerNameHash      OCTET STRING, -- Hash of Issuer's DN
	 *        issuerKeyHash       OCTET STRING, -- Hash of Issuers public key
	 *      serialNumber        CertificateSerialNumber
	 *    }
	 */
	const MAP = [
		'type'     => Identifier::SEQUENCE,
		'children' => [
			'hashAlgorithm'  => [ 'type' => AlgorithmIdentifier::MAP ],
			'issuerNameHash' => [ 'type' => Identifier::OCTETSTRING ],
			'issuerKeyHash'  => [ 'type' => Identifier::OCTETSTRING ],
			'serialNumber'   => [ 'type' => CertificateSerialNumber::MAP ],

		],
	];
}

abstract class Signature
{
	/**
	 * Signature       ::=     SEQUENCE {
	 *        signatureAlgorithm   AlgorithmIdentifier,
	 *        signature            BIT STRING,
	 *        certs                [0] EXPLICIT SEQUENCE OF Certificate OPTIONAL
	 * }
	 */
	const MAP = [
		'type'     => Identifier::SEQUENCE,
		'children' => [
			'signatureAlgorithm' => [ 'type' => AlgorithmIdentifier::MAP ],
			'signature'          => [ 'type' => Identifier::BITSTRING ],
			'certs'              => [
				'type'     => Certificate::MAP,
				'optional' => true,
				'explicit' => true,
				'constant' => 0,
			],

		],
	];
}
```

**Comment by adapik** [comment]
Please feel free to make a PR.

Probably it's not a bad idea to add mapping class for OCSPResponse also?

**Comment by Falseclock** [comment]
> Please feel free to make a PR.
> 
> Probably it's not a bad idea to add mapping class for OCSPResponse also?

ну вообще собирался... сейчас собираю ASN.1 запись для тестов... если что, сделаю и закину...

Думал вдруг уже имеется наработка

**Comment by Falseclock** [comment]
че-та я начинаю сомневаться, что мой PR будет принят )))

там новых файлов только больше 30 штук

**Comment by Falseclock** [comment]
@Adapik а может отдельный бранч сделать? Я туда PR запульну. Это явно новая мажорная версия будет.

Сам глянь https://github.com/Adapik/CMS/compare/master...Falseclock:master

**Comment by Falseclock** [comment]
там и полный разбор unsigned data и формирование tSTInfo, revocationValues, пересборка самого CMS, в общем полный фарш, включая TSP и OCSP запросы и ответы

**Comment by adapik** [comment]
I would like to merge to CMS Library new **Maps** and **objects** (like _TimeStampToken_ etc.)

I cannot accept: you've added implicit dependency on curl (I prefer more abstract http clients like guzzle with no hard dependency on cURL, PHP streams, sockets, or non-blocking event loops). This library initially only provides helpers for common ASN1 structures. I suppose if you should make external http request you should create separate library and name it like php-ocsp-client, php-tsp-client (or server side also), you can use CMS library as a dependency for creating requests and interpreting responses.

I think for you purpose you can create some factories to create new CMS structures from scratch or from existent CMS, not modifying original objects, cause you can put your objects into an invalid state. I would like to notice that when you adding revocation values it can be not only OCSPResponse but CRL also. And there are a lot of attributes like RevocationRefs, EscTimeStampToken etc. For me you solution is not the complete one.

As a conclusion, I suggest leave them as separate libraries, it would be a lot of work to redesign it.
I hope you was enjoing using this library, I understand you needs and I would like to return to some of your job later to rework this library somehow to fulfill them.

**Comment by Falseclock** [comment]
No problem, I can move CMS modifying methods to my own packages and make dependancy to yours.

**Comment by adapik** [comment]
@Falseclock , thank you!

**Comment by Falseclock** [comment]
almost done

here is my extended package
https://github.com/Falseclock/AdvancedCMS

this is difference https://github.com/Adapik/CMS/compare/master...Falseclock:master

unfortunately without test cases yet

**Comment by Falseclock** [comment]
https://github.com/Adapik/CMS/pull/4
